InvoiceApp/ViewModels/Company/CompanyInfoViewModel.cs
namespace InvoiceApp.ViewModels.Company
{
    public class CompanyInfoViewModel
    {
        public Data.Models.Company Company { get; set; }
    }
}

InvoiceApp/ViewModels/Company/CompanyViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace InvoiceApp.ViewModels.Company
{
    public class CompanyViewModel
    {
        public int? Id { get; set; }

        [Required(ErrorMessage = "Input the name")]
        [StringLength(100, MinimumLength = 1, ErrorMessage = "Input the name")]
        public string Name { get; set; }
    }
}

InvoiceApp/ViewModels/Company/IndexViewModel.cs
using InvoiceApp.Data.RequestParameters;
using InvoiceApp.Helpers;

namespace InvoiceApp.ViewModels.Company
{
    public class IndexViewModel
    {
        public PagedList<Data.Models.Company> Companies { get; set; }

        public CompanyRequestParameters Parameters { get; set; }
    }
}

InvoiceApp/Controllers/CompanyController.cs
using InvoiceApp.Data.Models;
using InvoiceApp.Data.RequestParameters;
using InvoiceApp.Helpers.Exceptions;
using InvoiceApp.Services.Interfaces;
using InvoiceApp.ViewModels.Company;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace InvoiceApp.Controllers
{
    public class CompanyController : Controller
    {
        private readonly ICompanyService _companyServce;


        public CompanyController(ICompanyService companyService)
        {
            _companyServce = companyService;
        }


        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Index([FromQuery] CompanyRequestParameters parameters)
        {
            var companies = await _companyServce.Get(parameters);
            return View(new IndexViewModel()
            {
                Parameters = parameters,
                Companies = companies
            });
        }


        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Create()
        {
            return View(new CompanyViewModel());
        }


        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(CompanyViewModel viewModel, string? returnUrl)
        {
            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }

            Company? company;

            try
            {
                company = await _companyServce.Create(viewModel);
            }
            catch (ModelValidationException e)
            {
                ModelState.AddModelError(e.Propery, e.Message);
                return View(viewModel);
            }

            if (company is null)
            {
                throw new AppException("Company is not created!");
            }

            return RedirectToAction(nameof(Details), new { id = company.Id, returnUrl = returnUrl });
        }


        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Edit(int id)
        {
            var company = await _companyServce.GetById(id);
            if (company is null)
            {
                throw new NotFoundException("Company is not found.");
            }

            return View(new CompanyViewModel()
            {
                Id = company.Id,
                Name = company.Name,
            });
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Edit(CompanyViewModel viewModel, string? returnUrl)
        {
            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }

            Company? updatedCompany;

            try
            {
                updatedCompany = await _companyServce.Update(viewModel);
            }
            catch (ModelValidationException e)
            {
                ModelState.AddModelError(e.Propery, e.Message);
                return View(viewModel);
            }

            if (updatedCompany is null)
            {
                throw new AppException("Company is not updated!");
            }

            return string.IsNullOrEmpty(returnUrl)
                ? RedirectToAction(nameof(Details), new { id = updatedCompany.Id })
                : Redirect(returnUrl);
        }


        [HttpDelete]
        [Authorize]
        public async Task<IActionResult> Delete(int id)
        {
            var isDeleted = await _companyServce.Delete(id);

            return isDeleted ? Ok() : BadRequest();
        }


        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Details(int id)
        {
            var company = await _companyServce.GetById(id);
            if (company is null)
            {
                throw new NotFoundException("Company is not found.");
            }

            return View(new CompanyInfoViewModel()
            {
                Company = company
            });
        }
    }
}

InvoiceApp/Controllers/StatisticsController.cs
using InvoiceApp.Services.Interfaces;
using InvoiceApp.ViewModels.Statistics;
using Microsoft.AspNetCore.Mvc;

namespace InvoiceApp.Controllers
{
	public class StatisticsController : Controller
	{
		private readonly IStatisticsService _statisticsService;
		public StatisticsController(IStatisticsService statisticsService)
		{
			_statisticsService = statisticsService;
		}


		[HttpGet]
		public async Task<IActionResult> Index([FromQuery] StatisticRequestViewModel requestVM, string? returnUrl)
		{
			ViewData["returnUrl"] = returnUrl;

			if (Request.Query.Count < 2)
			{
				return View(new IndexViewModel());
			}

			var statistics = await _statisticsService.GetYearRevenueStatistics(requestVM);

			return View(new IndexViewModel()
			{
				StatisticsRequest = requestVM,
				Statistics = statistics,
			});
		}
	}
}

InvoiceApp/Views/Company/Create.cshtml
@using InvoiceApp.Helpers;
@using InvoiceApp.ViewModels.Company;

@model CompanyViewModel;

@{
	ViewData["Title"] = "Create company";
	var returnUrl = Context.Request.Query.GetByKey("returnUrl", Url.Action("Index", "Company"));
}


<h2>Create company</h2>
<hr class="mb-3"/>

@await Html.PartialAsync("_CompanyForm", Model, new ViewDataDictionary(ViewData)
{
	{"Controller", "Company"}, {"Action", "Create"}, {"ButtonName", "Create"}, {"returnUrl", returnUrl}
})

<div class="container my-3 p-0">
	<a href="javascript: history.go(-1)" class="link link-primary">Back</a>
</div>

InvoiceApp/Views/Company/Details.cshtml
@using InvoiceApp.Data.RequestParameters;
@using InvoiceApp.Helpers;
@using InvoiceApp.ViewModels.Company;
@using InvoiceApp.ViewModels.Statistics;
@using Microsoft.AspNetCore.Http.Extensions;
@using System.Web;
@model CompanyInfoViewModel

@{
	ViewData["Title"] = "Company details";
	var returnUrl = Context.Request.Query.GetByKey("returnUrl", Url.Action("Index", "Company"));
	var currentUrl = Context.Request.GetDisplayUrl();
	var invoicesHref = Url.Action("List", "Invoice", new InvoiceRequestParameters()
	{ 
		CompanyName = Model.Company.Name 
	});

	var statisticsHref = Url.Action("Index", "Statistics", new StatisticRequestViewModel()
	{
		Companies = new List<string>() { Model.Company.Name }
	}) + $"&returnUrl={HttpUtility.UrlPathEncode(returnUrl)}";
}

<h2>Company details</h2>
<hr class="mb-3" />

<div class="container d-grid gap-1 gap-md-0">
	<div class="row">
		<div class="col-md-2 col-12 m-0  fw-bold">Name</div>
		<div class="col-md-10 col-12 m-0 ">@Model.Company.Name</div>
	</div>
	<div class="row">
		<div class="col-md-2 col-12 m-0  fw-bold">Invoices</div>
		<div class="col-md-10 col-12 m-0 "><a href="@invoicesHref" class="link link-primary">View</a></div>
	</div>
	<div class="row">
		<div class="col-md-2 col-12 m-0  fw-bold">Statistics</div>
		<div class="col-md-10 col-12 m-0 "><a href="@statisticsHref" class="link link-primary">View</a></div>
	</div>
</div>

<div class="container my-3">
	<a asp-action="Edit" asp-controller="Company" asp-route-id="@Model.Company.Id" asp-route-returnUrl="@currentUrl" class="link link-primary">Edit</a>
</div>

<div class="container">
	<a href="@returnUrl" class="link link-primary">Back</a>
</div>

InvoiceApp/Views/Company/Edit.cshtml
@using InvoiceApp.Helpers;
@using InvoiceApp.ViewModels.Company;

@model CompanyViewModel;

@{
	ViewData["Title"] = "Edit company";
	var returnUrl = Context.Request.Query.GetByKey("returnUrl", Url.Action("List", "Invoice"));
}


<h2>Edit company</h2>
<hr class="mb-3"/>

@await Html.PartialAsync("_CompanyForm", Model, new ViewDataDictionary(ViewData)
{
	{"Controller", "Company"}, {"Action", "Edit"}, {"ButtonName", "Save"}, {"returnUrl", returnUrl}
})


<div class="container my-3 p-0">
	<a href="javascript: history.go(-1)" class="link link-primary">Back</a>
</div>

InvoiceApp/Views/Company/Index.cshtml
@using InvoiceApp.ViewModels.Company;
@using InvoiceApp.ViewModels.Components;
@using Microsoft.AspNetCore.Http.Extensions;

@model IndexViewModel; 

@{
    ViewData["Title"] = "Companies";
    var deletionModalId = "deletion-modal";
    var returnUrl = Context.Request.GetDisplayUrl();
}

<form asp-controller="Company"
      asp-action="Index"
      method="get"
      class="search-form container card py-2 px-3 d-grid gap-2"
>
    <div class="row p-0">
        <div class="col-md-2 col-12 p-0 ">
            <label class="form-label">Name:</label>
        </div>
        <div class="col-md-10 col-12 p-0">
            <input asp-for="@Model.Parameters.Name" type="text" value="@Model.Parameters.Name" class="form-control"/>
        </div>
    </div>

    <div class="row p-0">
        <div class="col p-0 d-flex justify-content-end align-items-center gap-2">
            <a asp-controller="Company" asp-action="Index" class="btn btn-warning m-0">Clear</a>
            <input value="Search" type="submit" class="btn btn-primary m-0" />
        </div>
    </div>
</form>

<div class="my-2">
    <a asp-controller="Company" asp-action="Create" asp-route-returnUrl="@returnUrl" class="btn btn-primary">Create</a>
</div>

<div class="table-wrapper mb-2">
    <table class="table fs-6">
        <thead>
            <tr>
                <th scope="col" style="width:10%">Id</th>
                <th scope="col" style="width:75%">Name</th>
                <th scope="col" style="width:15%"></th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Companies is not null)
            {
                foreach (var item in Model.Companies)
                {
                    var editHref = Url.Action("Edit", "Company", new
                    {
                        id = item.Id,
                        returnUrl = Url.Action("Details", "Company", new{id = item.Id, returnUrl = returnUrl})
                    });

                    <tr>
                        <td>@item.Id</td>
                        <td>@item.Name</td>
                        <td>
                            <a asp-controller="Company" asp-action="Details" asp-route-id="@item.Id" asp-route-returnUrl="@returnUrl" class="btn btn-sm btn-info">Info</a>
                            <a href="@editHref" class="btn btn-sm btn-warning">Edit</a>
                            <button 
                                data-modal="@deletionModalId" data-id="@item.Id"
                                data-ondelete="this.closest('tr').remove()"
                                class ="btn btn-sm btn-danger"
                            >
                                Delete
                            </button>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>


@await Component.InvokeAsync("Pagination", new PaginationViewModel()
{
    ActionName = "Index",
    ControllerName = "Company",
    Data = Model.Companies,
    Parameters = Model.Parameters
})

<div class="container my-3 p-0">
	<a asp-controller="Invoice" asp-action="Index" class="link link-primary">Back</a>
</div>

@await Component.InvokeAsync("DeletionModal", new DeletionModalViewModel()
{
    ModalId = deletionModalId,
    Message = "Are you sure?",
    ActionUrl = Url.Action("Delete", "Company")
})

InvoiceApp/Views/Company/_CompanyForm.cshtml
@using InvoiceApp.ViewModels.Company;

@model CompanyViewModel;

@{
	var returnUrl = (string?)ViewData["returnUrl"];
}

<form asp-controller="@ViewData["Controller"]"
	  asp-action="@ViewData["Action"]" method="post"
	  class="container d-grid gap-3 p-2 card">
	<input asp-for="@Model.Id" type="hidden" value="@Model.Id" />

	<div class="row form-group gy-1">
		<div class="col-md-2 col-12">
			<label asp-for="@Model.Name">Name: </label>
		</div>
		<div class="col-md-10 col-12">
			<input asp-for="@Model.Name" type="text" value="@Model.Name" class="form-control" />
			<span asp-validation-for="@Model.Name" class="text-danger"></span>
		</div>
	</div>

	<div class="row form-group gy-1">
		<div class="col-12 text-md-end text-center">
			<input type="submit" value="@ViewData["ButtonName"]" class="btn btn-primary" />
		</div>
	</div>

	@if(!string.IsNullOrEmpty(returnUrl))
	{
		<input name="returnUrl" type="hidden" value="@returnUrl" />
	}
</form>